services:
  mongo1:
    image: mongo:7
    hostname: mongo1
    container_name: mongo1
    networks:
      - default
    ports:
      - "127.0.0.1:27017:27017"
    command: ["mongod", "--replSet", "myReplicaSet", "--bind_ip_all"]
    volumes:
      - mongo1_data:/data/db

  mongo2:
    image: mongo:7
    hostname: mongo2
    container_name: mongo2
    networks:
      - default
    ports:
      - "127.0.0.2:27017:27017"
    command: ["mongod", "--replSet", "myReplicaSet", "--bind_ip_all"]
    volumes:
      - mongo2_data:/data/db

  mongo3:
    image: mongo:7
    hostname: mongo3
    container_name: mongo3
    networks:
      - default
    ports:
      - "127.0.0.3:27017:27017"
    command: ["mongod", "--replSet", "myReplicaSet", "--bind_ip_all"]
    volumes:
      - mongo3_data:/data/db

  mongosetup:
    image: mongo:7
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    networks:
      - default
    volumes:
      - ./scripts:/scripts
    restart: "no"
    entrypoint: ["bash", "/scripts/mongo_setup.sh"]

networks:
  default:

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data: